### ISSUE TITLE
Crash with enumcreaturetype

### ISSUE THREAD

**Issue by EnderT5** [kegare/Cavern#1]
crash is fixed when i remove the cavern mod, it isnt a abyssalcraft bug.

http://pastebin.com/gujLspkw

**Comment by kegare** [comment]
Please try to change some config.
cavern-dimension.cfg -> **I:monsterSpawn=0**
caveland-dimension.cfg -> **I:monsterSpawn=0**

**Comment by kegare** [comment]
Also, please try to check in minimum environment.
(Install only: Forge, Cavern)

Cavern mod may not be the cause

**Comment by kegare** [comment]
Fixed on 1.0.7 build.
