### ISSUE TITLE
1.10.2: Crash when trying the cavelands world (the sapling one)

### ISSUE THREAD

**Issue by mrtopf** [kegare/Cavern#14]
The emerald one worked but when trying to get to the caveland dimension it crashed with this crashlog:

https://gist.github.com/mrtopf/9c55c627ca6ec9d144b9944e0de02ee5

Does the same when trying to load the world again:

**Comment by kegare** [comment]
Thanks!
This issue fixed on 1.4.2 build :D

**Comment by mrtopf** [comment]
I have to thank you for fixing it! :-)

Seems to work now!
