### ISSUE TITLE
The Escape Mission book is duplicated when entering portals

### ISSUE THREAD

**Issue by MCJediYoda** [kegare/Cavern#15]
The Escape Mission book is duplicated every time when traveling through one of the cavern portals. 

Minecraft Version: 1.10.2
Forge Version: 12.18.2.2125
Cavern Version: 1.10.2-v1.5.1

I:caveborn=1
B:cavernEscapeMission=true

I just need the book the first time I enter a new world.

Thanks

**Comment by kegare** [comment]
This issue fixed on 1.5.2 build.
Thanks for report :)

**Comment by MCJediYoda** [comment]
thanks a lot.  loving the mod and its perfect for my mod pack
