### ISSUE TITLE
Mod issue on 1.11

### ISSUE THREAD

**Issue by RedBullSlurpie** [kegare/Cavern#16]
Hello there. The issue I am having with your mod on 1.11 in my small pack i've created is that your mod will not allow me to load into a world. So, quickly through together a 1.11 modpack to test some mods and such and begin creating a 1.11 pack, well upon creating a world, it gets stuck on building terrain. No crash, ever, and when I remove your mod, the problem is solved and world loads. Only other info i can give you is Forge version, and what mods I have installed if you'd like. Let me know, hope to get this solved as your mod is awesome! :)

**Comment by Kisonu** [comment]
Same issue!

**Comment by kegare** [comment]
What's your mod versions?

**Comment by kegare** [comment]
This issue fixed on 1.6.0 beta. Thanks!
