### ISSUE TITLE
How to "Escape" the cavern quest?

### ISSUE THREAD

**Issue by MCJediYoda** [kegare/Cavern#22]
I have all the cavern achievements completed.  I am Diamond miner rank.  I made the portal with the orb.  I am unable to travel to the overworld or nether.  Is there something I am missing.  I am using 1.10.2.  I have enabled cave born in the ruins cavern and enabled escape mission.

**Comment by kegare** [comment]
Thanks for report.
This issue fixed on 1.7.4 build.

**Comment by MCJediYoda** [comment]
Thanks for the amazingly awesome mod.
