### ISSUE TITLE
miningPointItems not registering

### ISSUE THREAD

**Issue by MCJediYoda** [kegare/Cavern#26]
It seems that the items that I have in miningPointItems are not registering.  When I mine an ore with any tool I do not get any points.  This worked in 1.10.2-1.5.5 but not in 1.10.2-1.7.4.  I updated my mining list for 1.11.2 and only the first item in the miningPointItems seems to work.  Can you verify that the miningPointItems is working.  Here is part of my config for 1.10.2:

 Specify the items that can getting mining point. (Or Automatically decide if not specified)
   Note: If multiplayer, server-side only.
    S:miningPointItems <
        mekanism:AtomicDisassembler
        minecraft:iron_pickaxe
        minecraft:wooden_pickaxe
        minecraft:stone_pickaxe
        minecraft:diamond_pickaxe        
        minecraft:golden_pickaxe
        cavern:aquamarine_pickaxe
        cavern:magnite_pickaxe
        cavern:hexcite_pickaxe
        cavern:ice_pickaxe
        mekanismtools:WoodPaxel
        mekanismtools:StonePaxel
        mekanismtools:IronPaxel
        mekanismtools:DiamondPaxel
        mekanismtools:GoldPaxel
        mekanismtools:ObsidianPaxel
        mekanismtools:ObsidianPickaxe
        mekanismtools:LapisLazuliPaxel
        mekanismtools:LapisLazuliPickaxe
        mekanismtools:OsmiumPaxel
        mekanismtools:OsmiumPickaxe
        mekanismtools:BronzePaxel
        mekanismtools:BronzePickaxe
        mekanismtools:GlowstonePaxel
        mekanismtools:GlowstonePickaxe
        mekanismtools:SteelPaxel
        mekanismtools:SteelPickaxe
        roots:livingPickaxe
        tconstruct:pickaxe
        tconstruct:hammer
        sparkshammers:hammerIron:538
        sparkshammers:hammerWood:9
        sparkshammers:hammerStone:13
        sparkshammers:hammerGold
        sparkshammers:hammerDiamond
        sparkshammers:hammerCopper
        sparkshammers:hammerSilver
        sparkshammers:hammerTin
        sparkshammers:hammerLead
        sparkshammers:hammerNickel
        sparkshammers:hammerBronze
        sparkshammers:hammerSteel
        sparkshammers:hammerElectrum
        sparkshammers:hammerAluminium
        sparkshammers:hammerOsmium
        sparkshammers:hammerIridium
        sparkshammers:hammerMjolnir
        sparkshammers:hammerMini
        sparkshammers:hammerGiant
        sparkshammers:hammerNetherstar
        mysticalagriculture:supremium_pickaxe
     >

Also,  Can you check the mobs spawning in the ruins dimension in the latest Cavern version.  The mobs seem to spawn very very rarely.  Can you allow the config options like  I:monsterSpawn=200 in the ruins config?  I noticed in the WorldProviderRuinsCavern  you have getMonsterSpawn() returning 0 not sure if that could be part of the problem with mobs spawning in the ruins dimension.

I been playing with the latest version and nice job, I just need to update these two things and then the mod will be super amazing for my modpacks.

Thanks for your hard work on this :)

**Comment by mhallice** [comment]
I ran into the same issue, solved it by adding to "# Specify the mining point for each block."
Example:  S:miningPoints <
        minecraft:stone:stone,1
     >
This would give 1 point for every stone you mine....


Basic ones are as followed:
       minecraft:coal_ore
       minecraft:diamond_ore
       minecraft:gold_ore
       minecraft:iron_ore
       minecraft:lapis_ore
       minecraft:redstone_ore
       minecraft:lit_redstone_ore


Hope this helps :) if you know a way to have it do all ore let me know but i couldnt get *ore to work :/

**Comment by MCJediYoda** [comment]
I was referring to miningPointItems for the tools being used to mine.  Its been fixed in the latest update.  I can't recall on the miningpoints for ore but does it auto detect the ores when the config is first generated?

**Comment by MCJediYoda** [comment]
this is working now.
