### ISSUE TITLE
Crashes With Latest Forge (2363)

### ISSUE THREAD

**Issue by kenijey** [kegare/Cavern#29]
[crash-2017-06-25_20.12.06-client.txt](https://github.com/kegare/Cavern/files/1100486/crash-2017-06-25_20.12.06-client.txt)

**Comment by kegare** [comment]
This is OptiFine issue, not Cavern.

**Comment by kenijey** [comment]
i really wonder what @sp614x would say...

**Comment by sp614x** [comment]
Forge is too old, recommended version is #2387.
Use preview OptiFine C4, it is compatible with latest Forge versions.
```
FML: MCP 9.40 Powered by Forge 14.21.0.2363 Optifine OptiFine_1.12_HD_U_C3_pre ...
```
