### ISSUE TITLE
Composite Tools Uncraftable - Unable to place Diamond Tools/Armor into Composite Book interface!

### ISSUE THREAD

**Issue by ScytheIronclaw** [kegare/Cavern#34]
The composite recipes call for Diamond Tool + Hexicite Tool = Composite Tool.

The composite interface will accept Hexicite Tools but not vanilla Diamond Tools.

Mod version: 1.8.9
Minecraft version: 1.12

**Comment by kegare** [comment]
Thanks for report.
This issue will be fixed on 1.9.1 build.
Please wait for a moment.

**Comment by kegare** [comment]
This issue fixed on 1.9.1.
