### ISSUE TITLE
[Mod Conflict with Astral Sorcery]Unable to place Diamond & Hexcite Swords/Axes in Composting Interface.

### ISSUE THREAD

**Issue by ScytheIronclaw** [kegare/Cavern#35]
This bug is caused by the mod Astral Sorcery.

Astral Sorcery Version: 1.12-1-6
Cavern Version: 1.9.1
Minecraft Version: 1.12
Forge Version: 14.21.1.2387

While the Astral Sorcery mod is installed, any Diamond, Hexcite Axes and Swords that are spawned in with Creative Mode or crafted cannot be placed into the Compositing Interface.

If Astral Sorcery is removed, the Diamond and Hexcite Axes and Swords that were already crafted or spawned in remain bugged and are still unable to be placed into the Compositing Interface.

If Astral Sorcery is removed, any newly crafted or spawned Diamond and Hexcite Axes and Swords can be placed in the Composting Interface.

How to reproduce:
Have both Astral Sorcery and Cavern Mod installed.
Craft or Spawn in a Diamond and Hexcite Sword or Axe
Open the Composting Interface
Attempt to insert the Diamond and HExcite Swords/Axes into the Composting Interface.

*I also submitted a bug report about this issue on the Astral Sorcery GitHub page.

**Comment by kegare** [comment]
Hmm..
I tested that, But it is works fine.
Actually,
If your Diamond/Hexcite equipment is damaged, you cannot use that item as compositing material.

**Comment by ScytheIronclaw** [comment]
For some reason I can't place Hexcite Axes or Swords in the interface.
What version of Minecraft Forge are you using to test? I'm using Forge version 14.21.1.2387

**Comment by kegare** [comment]
Yes, I tested it on 14.21.1.2387.

**Comment by ScytheIronclaw** [comment]
I just tested this with a new instance with the same Minecraft Forge version with just the Cavern Mod. Everything works fine.

I've deleted the Cavern Mod from my main instance and have re-downloaded the latest version. I even deleted the configuration folder. I'm going to see if that fixes this issue.

**Comment by ScytheIronclaw** [comment]
Oh, man! I just fixed the issue! You won't believe what causes it!
The creative menu!

If you get a Hexcite Sword, Diamond Sword, Hexcite Axe or Diamond Axe from the Creative Inventory, for some reason, the Compositing inventory won't accept it.

**Comment by ScytheIronclaw** [comment]
I solved the issue.
This is caused by a mod conflict with the mod Astral Sorcery.
When this mod is active, any Diamond Swords, Hexcite Swords, Diamond Axes, and Hexcite Axes have some sort of junk data attached to them that prevents them from being inserted into the Compositing interface. Even after the mod is removed, any of the swords and axes crafted/spawned in while Astral Sorcery was installed will remain bugged.

With Astral Sorcery disabled, any spawned/crafted Diamond&Hexcite Axes&Swords will function as intended.

**Comment by kegare** [comment]
This issue was finally fixed on 1.9.2 build.
