### ISSUE TITLE
Cavern dimensions creating backups of the dimension and then crashing server when entering/regening the dimensions.

### ISSUE THREAD

**Issue by gefailter71** [kegare/Cavern#37]
MC version: 1.12
Cavern version: v1.9.4
Forge version: 2420

When opening the Cavern menu(right-clicking a portal) which lets u choose which dimension to regen u then get a chat message about the world folder being backed up and the new one getting generated.
Regular players were able to see the message and as I checked server files there were compressed ZIP files named after the dimension in the server folder.

**Comment by kegare** [comment]
Thanks for report.
I just fixed this issue on 1.9.5 build.
