### ISSUE TITLE
[1.12] When right clicking on the portal and clicking regen, the server crashes.

### ISSUE THREAD

**Issue by ProsperCraft** [kegare/Cavern#38]
Crashlog- 
https://gist.github.com/ProsperCraft/65c95bdc022af26d7e5db43ffdd7f293

Forge 2420
Caverns 194

backup was checked.

ATM3 is removing this mod from the pack due to the bug.

**Comment by kegare** [comment]
Thanks for report.
I just fixed this issue on 1.9.5 build.
