### ISSUE TITLE
[MC 1.12.2] Cannot interact with world after going through a portal.

### ISSUE THREAD

**Issue by SilentChaos512** [kegare/Cavern#47]
### Versions
Minecraft: 1.12.2
Forge: 14.23.0.2493
Cavern: 1.10.1

### The Problem
Going through a portal loads the intended dimension, but I cannot interact with the world. Moving is almost impossible, and blocks cannot be placed or mined. I can go back to the overworld by switching to creative mode and flying through the portal, but that does not fix the issue. Logging out while inside the cave dimension, then logging back in will allow me to interact with the world. This issue can be reproduced with nothing but Cavern installed. I am not sure if this affects 1.12 or 1.12.1, but I have never seen this issue before.

Here is my log file: https://gist.github.com/SilentChaos512/e55447bb725934a8bb77eef589cde8ab. Line 113 shows a NoSuchMethodError, which may be the cause of the issue. It shows up in the console right after going through the portal.

**Comment by darkphan** [comment]
This is only with 1.12.2. I noticed this issue the other day with the previous version of Cavern as well, and had to roll a pack back to 1.12.1.

**Comment by C0rn3j** [comment]
Also running into this issue on forge 2512 and Cavern 1.10.2

**Comment by C0rn3j** [comment]
This was fixed in newly released version, you can close this.
