### ISSUE TITLE
1.10.2 Server error

### ISSUE THREAD

**Issue by Xobias** [kegare/Cavern#5]
We have just created a portal to the Cavern world and the following errors appeared in the server console. I have included the crash log file also.

`2:09:42 PM CONSOLE: thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$NeighborNotifyEvent@4b987fd9:
2:09:52 PM CONSOLE: thread/ERROR] [FML]: Index: 2 Listeners:
2:09:52 PM CONSOLE: thread/ERROR] [FML]: 0: NORMAL
2:09:52 PM CONSOLE: thread/ERROR] [FML]: 1: ASM: lumien.randomthings.handler.RTEventHandler@3005f1c0 notifyNeighbors(Lnet/minecraftforge/event/world/BlockEvent$NeighborNotifyEvent;)V
2:09:52 PM CONSOLE: thread/ERROR] [FML]: 2: ASM: net.olafkeijsers.fastleafdecay.LeafUpdateEventHandler@299e7c66 UpdateNeighbour(Lnet/minecraftforge/event/world/BlockEvent$NeighborNotifyEvent;)V
2:09:52 PM CONSOLE: thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.terraingen.PopulateChunkEvent$Post@7102e0dc:
2:09:59 PM CONSOLE: *********** has left.
2:10:02 PM CONSOLE: Watchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
2:10:02 PM CONSOLE: Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
2:10:02 PM CONSOLE: thread/ERROR] [FML]: Index: 1 Listeners:
2:10:02 PM CONSOLE: thread/ERROR] [FML]: 0: NORMAL
2:10:02 PM CONSOLE: thread/ERROR] [FML]: 1: ASM: INSTANCE onLavaLakes(Lnet/minecraftforge/event/terraingen/PopulateChunkEvent$Post;)V
2:10:02 PM CONSOLE: thread/ERROR] [FML]: 2: ASM: forestry.core.worldgen.WorldGenerator@ce41f7c populateChunk(Lnet/minecraftforge/event/terraingen/PopulateChunkEvent$Post;)V
2:10:02 PM CONSOLE: Watchdog/ERROR]: This crash report has been saved to: /home/minecraft/server2/mcmyadmin/Minecraft/./crash-reports/crash-2016-07-16_13.09.55-server.txt
2:10:02 PM CONSOLE: Shutdown Thread/INFO]: Stopping server`

The Caveworld worked OK and we have not tried the Aquacave.

[crash-2016-07-16_13.09.57-server.txt](https://github.com/kegare/Cavern/files/367294/crash-2016-07-16_13.09.57-server.txt)

**Comment by Claycorp** [comment]
Turn off the server watchdog. It's not useful in modded for this exact reason. So instead of it crashing you will just see a lag spike till it completes whatever it's doing.

You can do this by setting `max-tick-time=-1` All the watchdog does is crashes the server when a tick takes longer than the time set and loading up other dimensions or lots of heavy worldgen will trigger it even when the server is fine otherwise. (If you don't want to turn it off make it higher than 60 seconds. Time is entered in milliseconds.)
