### ISSUE TITLE
Summoned zombies never get damaged

### ISSUE THREAD

**Issue by C0rn3j** [kegare/Cavern#56]
Minecraft Version: 1.12.2

Forge 2517

Cavern_1.12.1-v1.10.2.jar

**Comment by kegare** [comment]
This is no problem.
Summoned monster cannot attack owner, and vice versa.

**Comment by C0rn3j** [comment]
That is fine, but they don't get damaged by enemy mobs either, they're practically immortal.

**Comment by kegare** [comment]
Yes, they are invincible because player created them by mana.
But, they will disappear after a while.

**Comment by kegare** [comment]
For example,
Zombie and Skeleton: 5 minutes
Cavenic Zombie: 3 minutes
Cavenic Skeleton: 2 minutes

**Comment by C0rn3j** [comment]
Ah I see, so I guess this is more of a documentation issue as it definitely confused me and a friend when we were playing ^^

https://github.com/kegare/Cavern/issues/53
