### ISSUE TITLE
Exception in server tick loop (server crash on startup)

### ISSUE THREAD

**Issue by Gamerbolts** [kegare/Cavern#6]
Hi, I downloaded the newest version of Cavern v1.0.9 and the client loaded just fine but trying to load the server I got a crash. Here is the log http://pastebin.com/4sPb6YsP

Any help is appreciated. Thank you!

**Comment by Claycorp** [comment]
1.0.9 is calling client side classes on the server side. Mod needs to be updated to fix this.

@kegare Please fix this ASAP as the mod will not start on servers at all. This is also the same issue as #7 and as an issue reported on curseforge: http://minecraft.curseforge.com/projects/cavern?comment=9

**Comment by kegare** [comment]
Thanks for report.
This issue fixes on 1.1.0
