### ISSUE TITLE
[1.12.2] Crash on World Load

### ISSUE THREAD

**Issue by hextrace** [kegare/Cavern#61]
Minecraft Version: 1.12.2
Forge Version: 14.23.1.2590
Caverns Version:  1.10.3
Crash Log:  https://paste.ee/p/pSXzN

Issue:
  When initially creating a world with the "Caveborn" setting enabled, the client crashes out.

Notes:
  This mod seems to crash out when attempting to place the player into the starting Cavern dimension as specified in the Caverns configuration file.  Restarting the client and loading the world after the crash poses no issues so the issue appears to be limited specifically to WorldGen and Player Spawning.

EDIT:  Forgot to include crash log.

**Comment by kegare** [comment]
This issue was fixed on version 1.10.4.
