### ISSUE TITLE
Please fix the "A new Cavern version is available" bug, thank you.

### ISSUE THREAD

**Issue by Yandols** [kegare/Cavern#8]
Every time a new file is released on curseforge I update Cavern immediately, but the in-game message still persists and is getting really annoying since I already have the latest version.

In `cavern-general.cfg` I've also set `B:versionNotify=false` but the update message still shows up in game, despite having this set to false and running on latest version.

I think you need to give this a check or two.

Thanks.

**Comment by kegare** [comment]
This issue fixed on 1.1.1
Thanks
